# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.1
language: swift
xcode_sdk: iphonesimulator10.1
cache: cocoapods
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/TLButton.xcworkspace -scheme TLButton-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
